import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Head from "next/head";
import Navbar from '../components/Navbar';
import Footer from '../components/Footer';
import PageLoader from '../components/PageLoader';
import ContactHelp from '../components/ContactHelp';
import { AuthProvider } from '../contexts/AuthContext';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "MCSE",
  description: "Generated by create next app",
  icons: {
    icon: [
      {
        url: "/favicon.svg", // /public path
        href: "/favicon.svg", // /public path
      },
    ],
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider>
          <div className="min-h-screen flex flex-col relative">
            <PageLoader />
            {/* Background video directly embedded in the layout */}
            <div className="fixed inset-0 z-0">
              <video
                autoPlay
                muted
                loop
                playsInline
                className="absolute w-full h-full object-cover opacity-80"
              >
                <source src="/bgfinal.mp4" type="video/mp4" />
              </video>
              <div className="absolute inset-0 bg-black/10"></div>
            </div>
            <Navbar />
            <main className="flex-grow z-10">
              {children}
            </main>
            <Footer />
            <ContactHelp />
          </div>
        </AuthProvider>
      </body>

    </html>
  );
}
